name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Triggers on every push to master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          # This pulls the variables you added to GitHub
          REACT_APP_SUPABASE_URL: ${{ vars.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_PUBLISHABLE_KEY: ${{ vars.REACT_APP_SUPABASE_PUBLISHABLE_KEY }}
          REACT_APP_UNLOCK_PASSWORD: ${{ secrets.REACT_APP_UNLOCK_PASSWORD }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          REACT_APP_MEDIA_SECRET: ${{ secrets.REACT_APP_MEDIA_SECRET }}
          # Add any other secrets here if they are needed for the build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
